# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191019_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
